In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Working with Dates

In [7]:
# Converting to datetime datatype

date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. Extract year

In [10]:
date['date_year'] = date['date'].dt.year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

2. Extract month

In [11]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [14]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

Extract Days

In [16]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,day_dow,date_day
0,2019-12-10,5628,25,3,2019,12,December,10,10
1,2018-08-15,3646,14,157,2018,8,August,15,15
2,2018-10-23,1859,25,1,2018,10,October,23,23
3,2019-08-17,7292,25,1,2019,8,August,17,17
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [17]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,day_dow,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6,6

In [21]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns = ['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,day_dow,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,10,1,Tuesday
1,2018-08-15,2018,8,August,15,15,2,Wednesday
2,2018-10-23,2018,10,October,23,23,1,Tuesday
3,2019-08-17,2019,8,August,17,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,6,Sunday

In [23]:
# is weekend

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)

date.drop(columns= ['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,day_dow,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,6,Sunday,1

Extract week of the year

In [29]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,day_dow,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,6,Sunday,1,1

Extract Quarter

In [30]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,day_dow,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,6,Sunday,1,1,1

Extract Semester

In [31]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,day_dow,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,6,Sunday,1,1,1,1

Extract Time elapsed between dates

In [32]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 3, 25, 8, 20, 59, 703602)

In [33]:
today - date['date']

0     2297 days 08:20:59.703602
1     2779 days 08:20:59.703602
2     2710 days 08:20:59.703602
3     2412 days 08:20:59.703602
4     2635 days 08:20:59.703602
                 ...
995   2725 days 08:20:59.703602
996   2666 days 08:20:59.703602
997   2514 days 08:20:59.703602
998   2579 days 08:20:59.703602
999   2353 days 08:20:59.703602
Name: date, Length: 1000, dtype: timedelta64[ns]

In [34]:
(today - date['date']).dt.days

0      2297
1      2779
2      2710
3      2412
4      2635
       ...
995    2725
996    2666
997    2514
998    2579
999    2353
Name: date, Length: 1000, dtype: int64

In [36]:
# months passed

np.round((today - date['date']) / np.timedelta64(30,'D'),0)

0      77.0
1      93.0
2      90.0
3      80.0
4      88.0
       ...
995    91.0
996    89.0
997    84.0
998    86.0
999    78.0
Name: date, Length: 1000, dtype: float64

In [37]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [38]:
time['date'] = pd.to_datetime(time['date'])

In [39]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [40]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extract Time out

In [41]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

Time Difference

In [42]:
today - time['date']

0     4483 days 07:30:59.703602
1     4347 days 08:40:59.703602
2     4833 days 07:59:59.703602
3     4135 days 07:49:59.703602
4     4532 days 09:09:59.703602
                 ...
995   5122 days 07:30:59.703602
996   4443 days 09:06:59.703602
997   4908 days 08:43:59.703602
998   5024 days 08:46:59.703602
999   4296 days 08:55:59.703602
Name: date, Length: 1000, dtype: timedelta64[ns]

In [43]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.873583e+08
1      3.756121e+08
2      4.176000e+08
3      3.572922e+08
4      3.915978e+08
           ...
995    4.425679e+08
996    3.839080e+08
997    4.240826e+08
998    4.341052e+08
999    3.712066e+08
Name: date, Length: 1000, dtype: float64

In [45]:
# in minutes
(today - time['date'])/np.timedelta64(1,'m')

0      6.455971e+06
1      6.260201e+06
2      6.960000e+06
3      5.954870e+06
4      6.526630e+06
           ...
995    7.376131e+06
996    6.398467e+06
997    7.068044e+06
998    7.235087e+06
999    6.186776e+06
Name: date, Length: 1000, dtype: float64

In [46]:
# in hour

(today - time['date'])/np.timedelta64(1,'h')

0      107599.516584
1      104336.683251
2      115999.999918
3       99247.833251
4      108777.166584
           ...
995    122935.516584
996    106641.116584
997    117800.733251
998    120584.783251
999    103112.933251
Name: date, Length: 1000, dtype: float64